spring:
#JPA Settings
  jpa:
    database: H2
    show-sql: true
#DB Settings
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driverClassName: org.h2.Driver
#H2 Settings
  h2:
    console:
      enabled: true
      path: /h2console
  devtools:
    livereload:
      enabled: true
server:
  port: 80
